--- 
""" модуль ios_command - отправляет команду show на устройство под управлением IOS и возвращает 
результат выполнения команды .

Модуль ios_command не поддерживает отправку команд в конфигурационном
режиме. Для этого используется отдельный модуль - ios_config. """

- name:  example with argumetns in task 
  hosts: cisco-routers
  gather_facts: false # для сетевого оборудования выключаем , т.к. используются свои модули для сбора фактов
  connection: local # для сетевого оборудования всегда указываем local 


  task: # пример задания всех аргументов в задаче (task)
    - name: run show version
      ios_command:
        host: "{{ inventory_hosts }}"
        commands: show version
        username: admin # задан прямо в таске 
        password: 1111 # так же задан в таске 
        transport: cli #  и этот тоже 

- name: example with argumetns in var from playbook # тут аргументы создаются как пременная clii затем 
  hosts: cisco-routers                              # передаются как переменная аргументу provider
  gather_facts: false
  connection: local

  vars:
    clii:
      host: "{{ inventory_hosts }}"
      username: admin
      password: 1111
      transport: cli

  task:
    - name: run show version
      ios_command:
        commands: show version
        provider: "{{ clii }}"


- name : example with argumetns in group_vars # самый удобный вариант , задавать аргументы в
  hosts: cisco-routers                        # каталоге group_vars.
  gather_facts: false
  connection: local

  task:
    - name: run show version
      ios_command:
        commands: show version
        provider: "{{ cli }}" # эта переменная заданна в файле group_vars/all.yml
