--- 

- name:  first example 
  hosts: cisco-routers
  gather_facts: false # для сетевого оборудования выключаем , т.к. используются свои модули для сбора фактов
  connection: local # для сетевого оборудования всегда указываем local 


  tasks: # пример задания всех аргументов в задаче (task)
    - name: run show version
      ios_command:
        commands: show version
      register: sh_vr # register находится на одном уровне с name , а не commands
    
    - name: Debug registred var 
      debug: var=sh_vr.stdout_lines

- name : second example
  hosts: cisco-routers
  gather_facts: false
  connection: local

  tasks:
    - name: run show commands
      ios_command:
        commands:
          - show ip int bri  # когда задаем две и более команды , то синтаксис 
          - show ip route    # немного другой , команды указываем как список yaml
      register: show_result

    - name: Debug registred var
      debug: var=show_result.stdout_lines

- name: example with wait_for
  hosts: cisco-routers
  gather_facts: false
  connection: local

  tasks: 
    - name: run ping  
      ios_command: 
        commands: ping 10.101.101.137 # отправляем пинг
        wait_for:  # далее проверяем есть ли в выводе фраза "Success..."
          - result[0] contains 'Success rate is 100 percent' # если фраза содержится то все ок
        retries: 2 # указываем кол-во попыток выполнить команду ( по умолчанию 10)
        interval: 10 # указываем интервал между попытками  